//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWork2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priyt
    {
        public int ID_PET { get; set; }
        public string Klichka { get; set; }
        public string Paroda { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Ves { get; set; }
        public Nullable<int> Rost { get; set; }
    }
}
